# Generated by Django 4.2.6 on 2023-10-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=20, unique=True, verbose_name="登录用户名"),
                ),
                ("password", models.CharField(max_length=256, verbose_name="加密密码")),
            ],
        ),
    ]
