# Generated by Django 4.2.6 on 2023-10-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                ("adminid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "adminname",
                    models.CharField(
                        max_length=50, null=True, unique=True, verbose_name="用户名"
                    ),
                ),
                (
                    "adminpass",
                    models.CharField(max_length=256, null=True, verbose_name="密码"),
                ),
                (
                    "penname",
                    models.CharField(max_length=20, null=True, verbose_name="昵称"),
                ),
                (
                    "pid",
                    models.IntegerField(default=0, max_length=10, verbose_name="部门"),
                ),
                (
                    "logintimes",
                    models.IntegerField(default=0, max_length=10, verbose_name="登录次数"),
                ),
                (
                    "lastlogindate",
                    models.DateTimeField(default=0, verbose_name="最后登录日期"),
                ),
                (
                    "lastloginip",
                    models.GenericIPAddressField(null=True, verbose_name="上次登录IP"),
                ),
                (
                    "islock",
                    models.IntegerField(default=0, max_length=10, verbose_name="状态"),
                ),
                (
                    "readonly",
                    models.SmallIntegerField(
                        default=0, max_length=1, verbose_name="是否只读"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, null=True, verbose_name="用户名"),
                ),
                ("url", models.CharField(max_length=255, null=True, verbose_name="密码")),
                ("msg", models.CharField(max_length=255, null=True, verbose_name="消息")),
                ("ip", models.CharField(max_length=50, null=True, verbose_name="IP")),
                (
                    "createdate",
                    models.DateTimeField(auto_now_add=True, verbose_name="日期"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdminLoginLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loginname",
                    models.CharField(max_length=50, null=True, verbose_name="用户名"),
                ),
                (
                    "loginip",
                    models.CharField(max_length=50, null=True, verbose_name="IP"),
                ),
                (
                    "logindate",
                    models.DateTimeField(auto_now_add=True, verbose_name="日期"),
                ),
                (
                    "loginmsg",
                    models.CharField(max_length=255, null=True, verbose_name="消息"),
                ),
                (
                    "loginstate",
                    models.SmallIntegerField(
                        max_length=1, null=True, verbose_name="状态"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdminMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, null=True, verbose_name="菜单名称"),
                ),
                (
                    "cname",
                    models.CharField(max_length=50, null=True, verbose_name="控制器名称"),
                ),
                (
                    "aname",
                    models.CharField(max_length=50, null=True, verbose_name="动作名称"),
                ),
                (
                    "dname",
                    models.CharField(max_length=255, null=True, verbose_name="附加参数"),
                ),
                (
                    "followid",
                    models.IntegerField(default=0, max_length=10, verbose_name="父级"),
                ),
                (
                    "ordnum",
                    models.IntegerField(default=0, max_length=10, verbose_name="菜单排序"),
                ),
                (
                    "islock",
                    models.IntegerField(default=0, max_length=10, verbose_name="状态"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdminPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, null=True, verbose_name="部门名称"),
                ),
                (
                    "ordnum",
                    models.IntegerField(default=0, max_length=10, verbose_name="排序"),
                ),
                ("page_list", models.TextField(verbose_name="页面权限")),
                ("cate_list", models.TextField(verbose_name="栏目权限")),
                (
                    "pagelever",
                    models.CharField(max_length=50, null=True, verbose_name="权限设置"),
                ),
                (
                    "pagelock",
                    models.SmallIntegerField(
                        default=0, max_length=1, verbose_name="审核设置"
                    ),
                ),
            ],
        ),
    ]
