# Generated by Django 4.2.6 on 2023-10-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0002_alter_admin_islock_alter_admin_logintimes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="pid",
            field=models.IntegerField(default=0, verbose_name="部门"),
        ),
    ]
