# Generated by Django 4.2.6 on 2023-10-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0004_alter_admin_lastlogindate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="lastlogindate",
            field=models.DateTimeField(blank=True, null=True, verbose_name="最后登录日期"),
        ),
    ]
