# Generated by Django 4.2.6 on 2023-10-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0005_alter_admin_lastlogindate"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttachmentGroup",
            fields=[
                ("aid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "gname",
                    models.CharField(max_length=50, null=True, verbose_name="部门名称"),
                ),
                ("ordnum", models.IntegerField(default=0, verbose_name="排序")),
                ("islock", models.IntegerField(default=0, verbose_name="状态")),
            ],
        ),
        migrations.AlterField(
            model_name="admin",
            name="lastlogindate",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="最后登录日期"),
        ),
    ]
