# Generated by Django 4.2.6 on 2023-11-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0006_attachmentgroup_alter_admin_lastlogindate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_url",
                    models.CharField(max_length=255, null=True, verbose_name="url地址"),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, null=True, verbose_name="文件名"),
                ),
                (
                    "file_ext",
                    models.CharField(max_length=50, null=True, verbose_name="文件后缀"),
                ),
                ("file_size", models.IntegerField(default=0, verbose_name="文件大小")),
                (
                    "file_type",
                    models.IntegerField(
                        default=0, help_text="1：图片，2：视频，3：其他", verbose_name="文件类型"
                    ),
                ),
                (
                    "file_update",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传的日期"),
                ),
                (
                    "file_local",
                    models.IntegerField(
                        default=0, help_text="1：本地，2：阿里云，3：七牛云", verbose_name="存放位置"
                    ),
                ),
                ("file_adminid", models.IntegerField(default=0, verbose_name="管理云id")),
                ("file_userid", models.IntegerField(default=0, verbose_name="用户id")),
                (
                    "file_ip",
                    models.CharField(max_length=50, null=True, verbose_name="传者上IP"),
                ),
                ("gid", models.IntegerField(default=0, verbose_name="分组")),
            ],
        ),
    ]
