# Generated by Django 4.2.6 on 2023-11-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0007_attachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "web_name",
                    models.CharField(max_length=255, null=True, verbose_name="网站名称"),
                ),
                (
                    "web_logo",
                    models.CharField(max_length=255, null=True, verbose_name="网站Logo"),
                ),
                (
                    "web_icp",
                    models.CharField(max_length=255, null=True, verbose_name="网站备案号"),
                ),
                (
                    "beian_num",
                    models.CharField(max_length=255, null=True, verbose_name="公安备案号"),
                ),
                (
                    "beian_url",
                    models.CharField(max_length=255, null=True, verbose_name="公安备案链接"),
                ),
                (
                    "seo_title",
                    models.CharField(max_length=255, null=True, verbose_name="网站优化标题"),
                ),
                (
                    "seo_key",
                    models.CharField(max_length=255, null=True, verbose_name="网站关键字"),
                ),
                (
                    "seo_desc",
                    models.CharField(max_length=255, null=True, verbose_name="网站描述"),
                ),
                (
                    "ct_name",
                    models.CharField(max_length=255, null=True, verbose_name="公司名称"),
                ),
                (
                    "ct_tel",
                    models.CharField(max_length=255, null=True, verbose_name="服务热线"),
                ),
                (
                    "ct_fax",
                    models.CharField(max_length=255, null=True, verbose_name="传真号码"),
                ),
                (
                    "ct_mobile",
                    models.CharField(max_length=255, null=True, verbose_name="手机号码"),
                ),
                (
                    "ct_email",
                    models.CharField(max_length=255, null=True, verbose_name="电子邮箱"),
                ),
                (
                    "ct_address",
                    models.CharField(max_length=255, null=True, verbose_name="公司地址"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="attachment",
            name="file_adminid",
            field=models.IntegerField(default=0, verbose_name="管理员id"),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="file_ip",
            field=models.CharField(max_length=50, null=True, verbose_name="上传者IP"),
        ),
    ]
