# Generated by Django 4.2.6 on 2023-11-02 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0008_webconfig_alter_attachment_file_adminid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="webconfig",
            old_name="ct_name",
            new_name="ct_company",
        ),
    ]
