# Generated by Django 4.2.6 on 2023-11-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0009_rename_ct_name_webconfig_ct_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                ("cateid", models.AutoField(primary_key=True, serialize=False)),
                ("catename", models.CharField(max_length=30, verbose_name="栏目名称")),
                ("followid", models.IntegerField(default=0, verbose_name="父ID")),
                (
                    "catetype",
                    models.IntegerField(
                        default=0,
                        help_text="-2：链接，-1：单页，1：文章，2：产品，3：招聘",
                        verbose_name="栏目类型",
                    ),
                ),
                (
                    "catenum",
                    models.IntegerField(
                        default=0, help_text="数字越小越靠前", verbose_name="排序"
                    ),
                ),
                (
                    "cateurl",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="链接"
                    ),
                ),
                (
                    "catelist",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="列表页模板"
                    ),
                ),
                (
                    "cateshow",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="内容页模板"
                    ),
                ),
                (
                    "catetitle",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="SEO标题"
                    ),
                ),
                (
                    "catekey",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="SEO关键字"
                    ),
                ),
                (
                    "catedesc",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="SEO描述"
                    ),
                ),
            ],
        ),
    ]
