# Generated by Django 4.2.6 on 2023-11-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0011_categorymodel_isblank_categorymodel_isfilter_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserGroupModel",
            fields=[
                ("gid", models.AutoField(primary_key=True, serialize=False)),
                ("gname", models.CharField(max_length=30, verbose_name="栏目名称")),
                (
                    "ordnum",
                    models.IntegerField(
                        default=0, help_text="数字越小越靠前", verbose_name="排序"
                    ),
                ),
            ],
        ),
    ]
