# Generated by Django 4.2.6 on 2023-11-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0012_usergroupmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorymodel",
            name="catepage",
            field=models.IntegerField(default=0, verbose_name="分页数量"),
        ),
        migrations.AlterField(
            model_name="usergroupmodel",
            name="gname",
            field=models.CharField(max_length=30, verbose_name="分组名称"),
        ),
    ]
