# Generated by Django 4.2.6 on 2023-11-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0013_categorymodel_catepage_alter_usergroupmodel_gname"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorymodel",
            name="categroup",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="阅读权限"
            ),
        ),
    ]
