# Generated by Django 4.2.6 on 2023-11-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0014_categorymodel_categroup"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(max_length=255, null=True, verbose_name="标题"),
                ),
                (
                    "pic",
                    models.CharField(max_length=255, null=True, verbose_name="缩略图"),
                ),
                ("ispic", models.IntegerField(default=0, verbose_name="图片")),
                ("classid", models.IntegerField(default=0, verbose_name="分类")),
                ("hits", models.IntegerField(default=0, verbose_name="热度")),
                ("islock", models.IntegerField(default=0, verbose_name="状态")),
                ("ontop", models.IntegerField(default=0, verbose_name="置顶")),
                ("isnice", models.IntegerField(default=0, verbose_name="推荐")),
                ("ordnum", models.IntegerField(default=0, verbose_name="排序")),
                ("upnum", models.IntegerField(default=0, verbose_name="赞")),
                ("downnum", models.IntegerField(default=0, verbose_name="踩")),
                ("isurl", models.IntegerField(default=0, verbose_name="链接")),
                (
                    "url",
                    models.CharField(max_length=255, null=True, verbose_name="链接地址"),
                ),
                ("createdate", models.IntegerField(default=0, verbose_name="创建时间")),
                ("lastupdate", models.IntegerField(default=0, verbose_name="更新时间")),
                ("intro", models.TextField(verbose_name="摘要")),
                (
                    "tags",
                    models.CharField(max_length=255, null=True, verbose_name="标签"),
                ),
                (
                    "seotitle",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="SEO标题"
                    ),
                ),
                (
                    "seokey",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="SEO关键字"
                    ),
                ),
                (
                    "seodesc",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="SEO描述"
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="别名"
                    ),
                ),
                (
                    "showskin",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="内容页模板"
                    ),
                ),
                (
                    "subid",
                    models.CharField(max_length=255, null=True, verbose_name="发布到其它栏目"),
                ),
                ("adminid", models.IntegerField(default=0, verbose_name="管理员")),
                ("isauto", models.IntegerField(default=0, verbose_name="定时发布")),
                ("view_groupid", models.IntegerField(default=50, verbose_name="阅读权限")),
                (
                    "tagslist",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="标签列表"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["id", "ontop", "ordnum", "classid", "islock"],
                        name="order",
                    ),
                    models.Index(fields=["id", "ontop"], name="ontop"),
                    models.Index(fields=["id", "ordnum"], name="ordnum"),
                    models.Index(
                        fields=["islock", "classid", "id", "subid"], name="where"
                    ),
                    models.Index(fields=["subid"], name="subid"),
                    models.Index(
                        fields=["islock", "isauto", "createdate"], name="isauto"
                    ),
                ],
            },
        ),
    ]
