# Generated by Django 4.2.6 on 2023-11-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0015_contentmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelNewsModel",
            fields=[
                ("newsid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cid",
                    models.IntegerField(default=0, unique=True, verbose_name="cid"),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("content", models.TextField(verbose_name="正文")),
            ],
        ),
        migrations.AlterField(
            model_name="contentmodel",
            name="downnum",
            field=models.IntegerField(default=0, verbose_name="踩数量"),
        ),
        migrations.AlterField(
            model_name="contentmodel",
            name="hits",
            field=models.IntegerField(default=0, verbose_name="人气"),
        ),
        migrations.AlterField(
            model_name="contentmodel",
            name="upnum",
            field=models.IntegerField(default=0, verbose_name="赞数量"),
        ),
    ]
