# Generated by Django 4.2.6 on 2023-11-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0016_modelnewsmodel_alter_contentmodel_downnum_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelPageModel",
            fields=[
                ("pageid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cid",
                    models.IntegerField(default=0, unique=True, verbose_name="cid"),
                ),
                ("piclist", models.TextField(verbose_name="图片集")),
                ("content", models.TextField(verbose_name="正文")),
            ],
        ),
        migrations.AlterField(
            model_name="modelnewsmodel",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="价格"
            ),
        ),
    ]
