# Generated by Django 4.2.6 on 2023-11-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0018_modelfieldmodel_modelmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagsModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(max_length=50, null=True, verbose_name="标题"),
                ),
                ("hits", models.IntegerField(default=0, verbose_name="热度")),
            ],
        ),
    ]
