# Generated by Django 4.2.6 on 2023-11-24 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0019_tagsmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ModelFieldModel",
        ),
        migrations.RemoveField(
            model_name="modelmodel",
            name="issys",
        ),
    ]
