# Generated by Django 4.2.6 on 2023-11-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0020_delete_modelfieldmodel_remove_modelmodel_issys"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelJobModel",
            fields=[
                ("jobid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cid",
                    models.IntegerField(default=0, unique=True, verbose_name="cid"),
                ),
                ("content", models.TextField(verbose_name="工作内容")),
                (
                    "work_address",
                    models.CharField(max_length=50, null=True, verbose_name="工作地点"),
                ),
                (
                    "work_nature",
                    models.CharField(max_length=50, null=True, verbose_name="工作性质"),
                ),
                (
                    "work_education",
                    models.CharField(max_length=50, null=True, verbose_name="学历要求"),
                ),
                (
                    "work_money",
                    models.CharField(max_length=50, null=True, verbose_name="薪资待遇"),
                ),
                (
                    "work_age",
                    models.CharField(max_length=50, null=True, verbose_name="工作年限"),
                ),
                (
                    "work_num",
                    models.CharField(max_length=50, null=True, verbose_name="招聘人数"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelProModel",
            fields=[
                ("proid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cid",
                    models.IntegerField(default=0, unique=True, verbose_name="cid"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=10, verbose_name="价格"
                    ),
                ),
                ("content", models.TextField(verbose_name="正文")),
                ("piclist", models.TextField(verbose_name="组图")),
            ],
        ),
    ]
