# Generated by Django 4.2.6 on 2023-11-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0021_modeljobmodel_modelpromodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentmodel",
            name="view_groupid",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="阅读权限"
            ),
        ),
    ]
