# Generated by Django 4.2.6 on 2023-12-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0022_alter_contentmodel_view_groupid"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("title", models.CharField(max_length=50, verbose_name="区块说明")),
                ("key", models.CharField(max_length=50, verbose_name="关键字")),
                (
                    "content",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="内容"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
