# Generated by Django 4.2.6 on 2023-12-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0023_blockmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvertModel",
            fields=[
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50, verbose_name="广告名称")),
                ("datalist", models.TextField(verbose_name="广告内容")),
                ("ordnum", models.IntegerField(default=0, verbose_name="排序")),
                ("islock", models.IntegerField(default=0, verbose_name="状态")),
                ("akey", models.CharField(max_length=10, verbose_name="关键字")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
