# Generated by Django 4.2.6 on 2023-12-05 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0024_advertmodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advertmodel",
            name="create_time",
        ),
        migrations.RemoveField(
            model_name="advertmodel",
            name="update_time",
        ),
    ]
