# Generated by Django 4.2.6 on 2023-12-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0025_remove_advertmodel_create_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobFormModel",
            fields=[
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("my_title", models.CharField(max_length=50, verbose_name="申请职位")),
                ("my_truename", models.CharField(max_length=50, verbose_name="姓名")),
                ("my_sex", models.IntegerField(default=0, verbose_name="性别")),
                ("my_age", models.IntegerField(default=0, verbose_name="年龄")),
                ("my_mobile", models.IntegerField(default=0, verbose_name="手机")),
                ("my_education", models.IntegerField(default=0, verbose_name="学历")),
                ("my_work_exp", models.TextField(verbose_name="工作经验")),
                ("my_intro", models.TextField(verbose_name="自我评价")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
