# Generated by Django 4.2.6 on 2023-12-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0026_jobformmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobformmodel",
            name="my_ip",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="发布IP"
            ),
        ),
    ]
