# Generated by Django 4.2.6 on 2023-12-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0027_jobformmodel_my_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobformmodel",
            name="islock",
            field=models.IntegerField(default=0, verbose_name="状态"),
        ),
    ]
