# Generated by Django 4.2.6 on 2023-12-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0031_linkmodel_alter_bookmodel_createdate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webconfig",
            name="link_class",
            field=models.IntegerField(default=0, verbose_name="分类开关"),
        ),
        migrations.AddField(
            model_name="webconfig",
            name="link_class_data",
            field=models.TextField(blank=True, null=True, verbose_name="链接分类"),
        ),
        migrations.AddField(
            model_name="webconfig",
            name="link_logo",
            field=models.IntegerField(default=0, verbose_name="LOGO链接"),
        ),
    ]
