# Generated by Django 4.2.6 on 2023-12-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0032_webconfig_link_class_webconfig_link_class_data_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("upass", models.TextField(max_length=256, verbose_name="密码")),
                (
                    "umoney",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=10, verbose_name="余额"
                    ),
                ),
                ("uname", models.CharField(max_length=50, verbose_name="邮箱")),
                ("uface", models.CharField(max_length=255, verbose_name="头像")),
                ("uid", models.IntegerField(default=0, verbose_name="会员组")),
                ("islock", models.IntegerField(default=0, verbose_name="状态")),
                (
                    "regdate",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册日期"),
                ),
                (
                    "regip",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="注册IP"
                    ),
                ),
                (
                    "lastlogindate",
                    models.DateTimeField(blank=True, null=True, verbose_name="上次登录日期"),
                ),
                (
                    "lastloginip",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="上次登录IP"
                    ),
                ),
                ("logintimes", models.IntegerField(default=0, verbose_name="登录次数")),
            ],
        ),
    ]
