# Generated by Django 4.2.6 on 2023-12-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0033_usermodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="uemail",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="邮箱"
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="uface",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="头像"
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="uname",
            field=models.CharField(max_length=50, verbose_name="用户名"),
        ),
    ]
