# Generated by Django 4.2.6 on 2023-12-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0034_usermodel_uemail_alter_usermodel_uface_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("gid", models.IntegerField(default=0, verbose_name="分组")),
                ("ckey", models.CharField(max_length=50, verbose_name="字段Key")),
                ("ctitle", models.CharField(max_length=50, verbose_name="字段名称")),
                ("cvalue", models.TextField(verbose_name="字段值")),
                ("ordnum", models.IntegerField(default=0, verbose_name="排序")),
                ("ctype", models.IntegerField(default=0, verbose_name="字段类型")),
                ("dvalue", models.TextField(verbose_name="字段默认值")),
                ("dtext", models.CharField(max_length=255, verbose_name="提示文字")),
                ("utype", models.IntegerField(default=0, verbose_name="上传类型")),
                ("rtype", models.IntegerField(default=0, verbose_name="排列方式")),
                ("issys", models.IntegerField(default=0, verbose_name="系统自带")),
                ("islock", models.IntegerField(default=0, verbose_name="状态")),
                ("ishide", models.IntegerField(default=0, verbose_name="是否隐藏")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["ckey"], name="ckey"),
                    models.Index(fields=["gid"], name="gid"),
                ],
            },
        ),
    ]
