# Generated by Django 4.2.6 on 2023-12-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0035_configmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigGroupModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="分组ID"
                    ),
                ),
                (
                    "gname",
                    models.CharField(max_length=50, null=True, verbose_name="分组名称"),
                ),
                ("ordnum", models.IntegerField(default=0, verbose_name="排序")),
                ("gkey", models.CharField(max_length=50, verbose_name="分组Key")),
                ("islock", models.IntegerField(default=0, verbose_name="状态")),
                ("types", models.IntegerField(default=0, verbose_name="类型")),
            ],
        ),
    ]
