# Generated by Django 4.2.6 on 2024-01-31 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0036_configgroupmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WebConfig",
        ),
        migrations.AlterField(
            model_name="configgroupmodel",
            name="types",
            field=models.IntegerField(default=0, verbose_name="分类"),
        ),
    ]
