# Generated by Django 4.2.6 on 2024-03-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0037_delete_webconfig_alter_configgroupmodel_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlugService",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, null=True, verbose_name="客服名称"),
                ),
                ("qq", models.CharField(max_length=50, null=True, verbose_name="QQ号码")),
                ("ordnum", models.IntegerField(default=0, verbose_name="排序")),
                ("islock", models.IntegerField(default=0, verbose_name="状态")),
            ],
        ),
    ]
