# Generated by Django 4.2.6 on 2024-03-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0038_plugservice"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorymodel",
            name="depth",
            field=models.IntegerField(default=1, verbose_name="深度"),
        ),
        migrations.AddField(
            model_name="categorymodel",
            name="parentid",
            field=models.IntegerField(default=0, verbose_name="所有父ID"),
        ),
        migrations.AddField(
            model_name="categorymodel",
            name="sonid",
            field=models.IntegerField(default=0, verbose_name="所有子ID"),
        ),
    ]
