# Generated by Django 4.2.6 on 2024-03-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0039_categorymodel_depth_categorymodel_parentid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorymodel",
            name="parentid",
            field=models.TextField(null=True, verbose_name="所有父ID"),
        ),
        migrations.AlterField(
            model_name="categorymodel",
            name="sonid",
            field=models.TextField(null=True, verbose_name="所有子ID"),
        ),
    ]
