# Generated by Django 4.2.6 on 2024-03-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0040_alter_categorymodel_parentid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "orderid",
                    models.CharField(max_length=50, null=True, verbose_name="订单号"),
                ),
                (
                    "pro_name",
                    models.CharField(max_length=255, null=True, verbose_name="产品名称"),
                ),
                ("pro_num", models.IntegerField(default=0, verbose_name="数量")),
                (
                    "pro_price",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=10, verbose_name="总金额"
                    ),
                ),
                (
                    "truename",
                    models.CharField(max_length=50, null=True, verbose_name="姓名"),
                ),
                (
                    "mobile",
                    models.CharField(max_length=20, null=True, verbose_name="手机"),
                ),
                (
                    "address",
                    models.CharField(max_length=255, null=True, verbose_name="收货地址"),
                ),
                ("remark", models.TextField(null=True, verbose_name="备注")),
                (
                    "createdate",
                    models.DateTimeField(auto_now_add=True, verbose_name="下单日期"),
                ),
                ("isover", models.IntegerField(default=0, verbose_name="状态")),
                ("ispay", models.IntegerField(default=0, verbose_name="付款状态")),
                (
                    "payway",
                    models.CharField(max_length=50, null=True, verbose_name="付款方式"),
                ),
                (
                    "trade_no",
                    models.CharField(max_length=255, null=True, verbose_name="交易号"),
                ),
                (
                    "postip",
                    models.CharField(max_length=50, null=True, verbose_name="IP地址"),
                ),
                ("userid", models.IntegerField(default=0, verbose_name="用户ID")),
            ],
        ),
    ]
