# Generated by Django 4.2.6 on 2024-03-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0041_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="createdate",
            field=models.IntegerField(default=0, verbose_name="下单日期"),
        ),
    ]
