# Generated by Django 4.2.6 on 2024-03-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0042_alter_order_createdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMoney",
            fields=[
                (
                    "aid",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("types", models.SmallIntegerField(default=0, verbose_name="性质")),
                (
                    "title",
                    models.CharField(max_length=255, null=True, verbose_name="名称|流水号"),
                ),
                ("userid", models.IntegerField(default=0, verbose_name="用户ID")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=10, verbose_name="金额"
                    ),
                ),
                (
                    "oldmoney",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=10, verbose_name="变动前"
                    ),
                ),
                (
                    "newmoney",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=10, verbose_name="变动后"
                    ),
                ),
                ("createdate", models.IntegerField(default=0, verbose_name="日期")),
            ],
        ),
    ]
