# Generated by Django 4.2.6 on 2024-03-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0043_usermoney"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, null=True, verbose_name="询价产品"),
                ),
                (
                    "truename",
                    models.CharField(max_length=50, null=True, verbose_name="姓名"),
                ),
                (
                    "mobile",
                    models.CharField(max_length=20, null=True, verbose_name="手机"),
                ),
                ("remark", models.TextField(null=True, verbose_name="备注")),
                ("createdate", models.IntegerField(default=0, verbose_name="提交日期")),
                ("isover", models.IntegerField(default=0, verbose_name="状态")),
                (
                    "postip",
                    models.CharField(max_length=50, null=True, verbose_name="IP地址"),
                ),
            ],
        ),
    ]
