# Generated by Django 4.2.6 on 2024-04-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0044_inquiry"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempMail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, null=True, verbose_name="用途"),
                ),
                (
                    "mail_title",
                    models.CharField(max_length=255, null=True, verbose_name="邮件标题"),
                ),
                ("mail_content", models.TextField(null=True, verbose_name="邮件内容")),
                ("islock", models.IntegerField(default=0, verbose_name="状态")),
                (
                    "mkey",
                    models.CharField(max_length=50, null=True, verbose_name="Key"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["id"], name="id"),
                    models.Index(fields=["mkey"], name="mkey"),
                ],
            },
        ),
    ]
